### ISSUE TITLE
I can't use casbin with falsk-authz and casbin-sqlalchemy-adapter

### ISSUE THREAD

**Issue by songkang1993** [pycasbin/flask-authz#39]
```
Traceback (most recent call last):
  File "E:/projects/flask-project/project-service/app.py", line 4, in <module>
    from routes import init_app
  File "E:\projects\flask-project\project-service\routes\__init__.py", line 1, in <module>
    from .base import CustomizeApi
  File "E:\projects\flask-project\project-service\routes\base.py", line 13, in <module>
    import casbin_sqlalchemy_adapter
  File "E:\projects\flask-project\venv\lib\site-packages\casbin_sqlalchemy_adapter\__init__.py", line 1, in <module>
    from .adapter import CasbinRule, Adapter, Base
  File "E:\projects\flask-project\venv\lib\site-packages\casbin_sqlalchemy_adapter\adapter.py", line 46, in <module>
    class Adapter(persist.Adapter, persist.adapters.UpdateAdapter):
AttributeError: module 'casbin.persist.adapters' has no attribute 'UpdateAdapter'
```

Becase flask-authz use casbin v1.0.4 and casbin v1.0.4 dosen't import UpdateAdapter to it's __init__. But last version of casbin imported it.
What should I do to use flask-authz with casbin-sqlalchemy-adapter?

**Comment by Zxilly** [comment]
We will later update the dependency of flask-authz.

**Comment by songkang1993** [comment]
> We will later update the dependency of flask-authz.

Now I use Casbin==1.8.1, it works for me.
